import { Metadata } from "next";
import "./globals.css";
import VisualEditsMessenger from "../visual-edits/VisualEditsMessenger";
import ErrorReporter from "@/components/ErrorReporter";
import Script from "next/script";
import { Prompt } from "next/font/google";

// 1. เพิ่ม "thai" ใน subsets เพื่อให้แสดงผลภาษาไทยได้ถูกต้อง
// 2. การระบุ subsets และ weight ที่ชัดเจนช่วยให้ Turbopack/Webpack โหลด Font ได้แม่นยำขึ้น
const prompt = Prompt({
  subsets: ["latin", "thai"], 
  weight: ["300", "400", "500", "600", "700"],
  display: "swap", // เพิ่มเพื่อให้ตัวอักษรแสดงผลทันทีระหว่างโหลด
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th"> {/* เปลี่ยนเป็น th เพื่อ SEO และการจัดการภาษาไทย */}
      <body className={`${prompt.className} antialiased`}>
        <ErrorReporter />
        <Script
          src="https://slelguoygbfzlpylpxfs.supabase.co/storage/v1/object/public/scripts//route-messenger.js"
          strategy="afterInteractive"
          data-target-origin="*"
          data-message-type="ROUTE_CHANGE"
          data-include-search-params="true"
          data-only-in-iframe="true"
          data-debug="true"
          data-custom-data='{"appName": "YourApp", "version": "1.0.0", "greeting": "hi"}'
        />
        {children}
        <VisualEditsMessenger />
      </body>
    </html>
  );
}